#!/bin/bash
#PBS -q normal
#PBS -l nodes=1:ppn=16:native
#PBS -l walltime=02:00:00
#PBS -N check_hot_512
#PBS -o Out/hot_512x512.out
#PBS -e Log/hot_512x512.log
#PBS -A TG-CCR120040
#PBS -M gregory.petropoulos@colorado.edu
#PBS -m abe
#PBS -V
# Start of user commands - comments start with a hash sign (#)
cd /oasis/scratch/gregp/temp_project/cs_5576/dilute-ising
mpirun -np 16 -hostfile $PBS_NODEFILE ./DIsing hot_512x512.pgm checkerboard 10 1 1000000 1000 1000
