#!/bin/bash
#PBS -q normal
#PBS -l nodes=64:ppn=16:native
#PBS -l walltime=01:00:00
#PBS -N check_cold_2048
#PBS -o Out/fls_64_2048x2048.out
#PBS -e Log/single_2048x2048.log
#PBS -A TG-CCR120040
#PBS -M gregory.petropoulos@colorado.edu
#PBS -m abe
#PBS -V
# Start of user commands - comments start with a hash sign (#)
cd /oasis/scratch/gregp/temp_project/cs_5576/dilute-ising
mpirun -np 1024 -hostfile $PBS_NODEFILE ./DIsing cold_2048x2048.pgm checkerboard 0.1 1 10000 0 0
